scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 15s
    static_configs:
      - targets: ['localhost:9090']
  - job_name: 'demo'
    scrape_interval: 15s
    static_configs:
      - targets: ['demo:8080']
